package courswork;

/**
 * ADPROC Coursework 2015.
 *
 * ORDER SYSTEM FOR A PIPE-SELLING COMPANY
 *
 * @authors 750430 & 750148
 */

/**
 * we can build some validation into here, i think that entails something like:
 * private static int maximumLengthOfPipe = 6 ... but need to think about this
 * the diameter is user defined, but needs some validation checking - maybe a double
 * 
 * need to implement some validation to display what is happening / valid / invalid pipe
 * 
 * also need to allow for multiple orders
 * 
 * @author up750430
 */

public class PipesRusGUI extends javax.swing.JFrame {

    /**
     * Creates new form PipesRusGUI
     */
    public PipesRusGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        plasticTypeGUILabel = new javax.swing.JLabel();
        innerInsulationGUILabel = new javax.swing.JLabel();
        outerReinforcementGUILabel = new javax.swing.JLabel();
        chemicalResistanceGUILabel = new javax.swing.JLabel();
        lengthGUILabel = new javax.swing.JLabel();
        outerDiameterGUILabel = new javax.swing.JLabel();
        innerInsulationGUIRBY = new javax.swing.JRadioButton();
        innerInsulationGUIRBN = new javax.swing.JRadioButton();
        plasticTypeGUIRB1 = new javax.swing.JRadioButton();
        plasticTypeGUIRB2 = new javax.swing.JRadioButton();
        plasticTypeGUIRB3 = new javax.swing.JRadioButton();
        plasticTypeGUIRB4 = new javax.swing.JRadioButton();
        plasticTypeGUIRB5 = new javax.swing.JRadioButton();
        outerReinforcementGUIRBY = new javax.swing.JRadioButton();
        outerReinforcementGUIRBN = new javax.swing.JRadioButton();
        plasticTypeGUIRBNI = new javax.swing.JRadioButton();
        innerInsulationGUIRBNI = new javax.swing.JRadioButton();
        outerReinforcementGUIRBNI = new javax.swing.JRadioButton();
        chemicalResistanceGUIRBY = new javax.swing.JRadioButton();
        chemicalResistanceGUIRBN = new javax.swing.JRadioButton();
        chemicalResistanceGUIRBNI = new javax.swing.JRadioButton();
        lengthGUITF1 = new javax.swing.JTextField();
        outerDiameterGUITF1 = new javax.swing.JTextField();
        lengthGUIMeters = new javax.swing.JRadioButton();
        lengthGUIInches = new javax.swing.JRadioButton();
        outerDiameterGUIMeters = new javax.swing.JRadioButton();
        outerDiameterGUIInches = new javax.swing.JRadioButton();
        colourGUILabel = new javax.swing.JLabel();
        colourGUIRBnoColour = new javax.swing.JRadioButton();
        colourGUIRB1Colour = new javax.swing.JRadioButton();
        colourGUIRB2Colour = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaGUI = new javax.swing.JTextArea();
        orderbuttonGUI = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jLabel6.setText("jLabel6");

        jTextField7.setText("jTextField7");

        jRadioButton6.setText("jRadioButton6");

        jRadioButton9.setText("jRadioButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quote", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N

        plasticTypeGUILabel.setText("Plastic Type:");

        innerInsulationGUILabel.setText("Inner Insulation: ");

        outerReinforcementGUILabel.setText("Outer Reinforcement:");

        chemicalResistanceGUILabel.setText("Chemical Resistance:");

        lengthGUILabel.setText("Length:");

        outerDiameterGUILabel.setText("Outer Diameter:");

        innerInsulationGUIRBY.setText("Yes");
        innerInsulationGUIRBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innerInsulationGUIRBYActionPerformed(evt);
            }
        });

        innerInsulationGUIRBN.setText("No");

        plasticTypeGUIRB1.setText("1");
        plasticTypeGUIRB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plasticTypeGUIRB1ActionPerformed(evt);
            }
        });

        plasticTypeGUIRB2.setText("2");

        plasticTypeGUIRB3.setText("3");
        plasticTypeGUIRB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plasticTypeGUIRB3ActionPerformed(evt);
            }
        });

        plasticTypeGUIRB4.setText("4");

        plasticTypeGUIRB5.setText("5");

        outerReinforcementGUIRBY.setText("Yes");
        outerReinforcementGUIRBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerReinforcementGUIRBYActionPerformed(evt);
            }
        });

        outerReinforcementGUIRBN.setText("No");
        outerReinforcementGUIRBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outerReinforcementGUIRBNActionPerformed(evt);
            }
        });

        plasticTypeGUIRBNI.setText("Not Important");
        plasticTypeGUIRBNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plasticTypeGUIRBNIActionPerformed(evt);
            }
        });

        innerInsulationGUIRBNI.setText("Not Important");

        outerReinforcementGUIRBNI.setText("Not Important");

        chemicalResistanceGUIRBY.setText("Yes");

        chemicalResistanceGUIRBN.setText("No");

        chemicalResistanceGUIRBNI.setText("Not Important");

        lengthGUITF1.setText("jTextField1");
        lengthGUITF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthGUITF1ActionPerformed(evt);
            }
        });

        outerDiameterGUITF1.setText("jTextField2");

        lengthGUIMeters.setText("Meters");

        lengthGUIInches.setText("Inches");

        outerDiameterGUIMeters.setText("Meters");

        outerDiameterGUIInches.setText("Inches");

        colourGUILabel.setText("Colour:");

        colourGUIRBnoColour.setText("No Colour");

        colourGUIRB1Colour.setText("1 Colour");

        colourGUIRB2Colour.setText("2 Colours");

        textAreaGUI.setColumns(20);
        textAreaGUI.setRows(5);
        textAreaGUI.setText("(\"This pipe is not available, please try changing your components.\")\n\n(\"This pipe costs £\" + \".\")");
        jScrollPane1.setViewportView(textAreaGUI);

        orderbuttonGUI.setText("Place Order");
        orderbuttonGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbuttonGUIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(colourGUILabel)
                            .addComponent(outerDiameterGUILabel)
                            .addComponent(lengthGUILabel)
                            .addComponent(chemicalResistanceGUILabel)
                            .addComponent(outerReinforcementGUILabel)
                            .addComponent(innerInsulationGUILabel)
                            .addComponent(plasticTypeGUILabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(colourGUIRBnoColour)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(colourGUIRB1Colour)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(colourGUIRB2Colour))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lengthGUITF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lengthGUIMeters)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lengthGUIInches))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(outerDiameterGUITF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(outerDiameterGUIMeters)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(outerDiameterGUIInches)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                                .addComponent(orderbuttonGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(plasticTypeGUIRB1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plasticTypeGUIRB2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plasticTypeGUIRB3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plasticTypeGUIRB4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plasticTypeGUIRB5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plasticTypeGUIRBNI))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(innerInsulationGUIRBY)
                                                .addGap(18, 18, 18)
                                                .addComponent(innerInsulationGUIRBN)
                                                .addGap(18, 18, 18)
                                                .addComponent(innerInsulationGUIRBNI))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(outerReinforcementGUIRBY)
                                                    .addComponent(chemicalResistanceGUIRBY))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(outerReinforcementGUIRBN)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(outerReinforcementGUIRBNI))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(chemicalResistanceGUIRBN)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(chemicalResistanceGUIRBNI)))))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plasticTypeGUILabel)
                    .addComponent(plasticTypeGUIRB1)
                    .addComponent(plasticTypeGUIRB2)
                    .addComponent(plasticTypeGUIRB3)
                    .addComponent(plasticTypeGUIRB4)
                    .addComponent(plasticTypeGUIRB5)
                    .addComponent(plasticTypeGUIRBNI))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(innerInsulationGUILabel)
                    .addComponent(innerInsulationGUIRBY)
                    .addComponent(innerInsulationGUIRBN)
                    .addComponent(innerInsulationGUIRBNI))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outerReinforcementGUILabel)
                    .addComponent(outerReinforcementGUIRBY)
                    .addComponent(outerReinforcementGUIRBN)
                    .addComponent(outerReinforcementGUIRBNI))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chemicalResistanceGUILabel)
                    .addComponent(chemicalResistanceGUIRBY)
                    .addComponent(chemicalResistanceGUIRBN)
                    .addComponent(chemicalResistanceGUIRBNI))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lengthGUILabel)
                            .addComponent(lengthGUITF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthGUIMeters)
                            .addComponent(lengthGUIInches))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outerDiameterGUILabel)
                            .addComponent(outerDiameterGUITF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outerDiameterGUIMeters)
                            .addComponent(outerDiameterGUIInches)))
                    .addComponent(orderbuttonGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourGUILabel)
                    .addComponent(colourGUIRBnoColour)
                    .addComponent(colourGUIRB1Colour)
                    .addComponent(colourGUIRB2Colour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void innerInsulationGUIRBYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innerInsulationGUIRBYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_innerInsulationGUIRBYActionPerformed

    private void plasticTypeGUIRB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plasticTypeGUIRB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plasticTypeGUIRB1ActionPerformed

    private void plasticTypeGUIRB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plasticTypeGUIRB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plasticTypeGUIRB3ActionPerformed

    private void outerReinforcementGUIRBYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerReinforcementGUIRBYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outerReinforcementGUIRBYActionPerformed

    private void outerReinforcementGUIRBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outerReinforcementGUIRBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outerReinforcementGUIRBNActionPerformed

    private void plasticTypeGUIRBNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plasticTypeGUIRBNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plasticTypeGUIRBNIActionPerformed

    private void lengthGUITF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthGUITF1ActionPerformed
        // text box for pipe length:
        
    }//GEN-LAST:event_lengthGUITF1ActionPerformed

    private void orderbuttonGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbuttonGUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderbuttonGUIActionPerformed

    /**
     * Validation of pipe length & diameter
     */
    private double pipeLength;
    private int PipeColour;
    private static final double minLength = 0.5; // the minimum length of pipe
    private static final double maxLength = 6.0; // the maximum length of pipe
    private double outerRadius;
    private int plasticGrade;
    private int quantityOfPipe;
    private static int minQty = 1; // the minimum quantities of pipe that can be ordered
    private static int maxQty = 100; // the maximum quantities of pipe that can be ordered
    private boolean isItInsulated;
    private boolean isItReinforced;
    private boolean checmicalResistant;
    private PipeColour pipeColour; //an object.
    private final PipeType pipeGrade;
    /**private static Order order;
    protected static double[] basicCost = {INSERT VALUES OF PIPES HERE}; // the basic cost of 1 sqm of pipe
    protected static double[] colourCost = {12,15}; // additional costs for colours
    protected static int sealableTopsCost = 5; // additional costs for insulation
    protected static int reinforcedBottomCost = 10; // additional costs for outer reinforcement
    */
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PipesRusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PipesRusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PipesRusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PipesRusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PipesRusGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chemicalResistanceGUILabel;
    private javax.swing.JRadioButton chemicalResistanceGUIRBN;
    private javax.swing.JRadioButton chemicalResistanceGUIRBNI;
    private javax.swing.JRadioButton chemicalResistanceGUIRBY;
    private javax.swing.JLabel colourGUILabel;
    private javax.swing.JRadioButton colourGUIRB1Colour;
    private javax.swing.JRadioButton colourGUIRB2Colour;
    private javax.swing.JRadioButton colourGUIRBnoColour;
    private javax.swing.JLabel innerInsulationGUILabel;
    private javax.swing.JRadioButton innerInsulationGUIRBN;
    private javax.swing.JRadioButton innerInsulationGUIRBNI;
    private javax.swing.JRadioButton innerInsulationGUIRBY;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton lengthGUIInches;
    private javax.swing.JLabel lengthGUILabel;
    private javax.swing.JRadioButton lengthGUIMeters;
    private javax.swing.JTextField lengthGUITF1;
    private javax.swing.JButton orderbuttonGUI;
    private javax.swing.JRadioButton outerDiameterGUIInches;
    private javax.swing.JLabel outerDiameterGUILabel;
    private javax.swing.JRadioButton outerDiameterGUIMeters;
    private javax.swing.JTextField outerDiameterGUITF1;
    private javax.swing.JLabel outerReinforcementGUILabel;
    private javax.swing.JRadioButton outerReinforcementGUIRBN;
    private javax.swing.JRadioButton outerReinforcementGUIRBNI;
    private javax.swing.JRadioButton outerReinforcementGUIRBY;
    private javax.swing.JLabel plasticTypeGUILabel;
    private javax.swing.JRadioButton plasticTypeGUIRB1;
    private javax.swing.JRadioButton plasticTypeGUIRB2;
    private javax.swing.JRadioButton plasticTypeGUIRB3;
    private javax.swing.JRadioButton plasticTypeGUIRB4;
    private javax.swing.JRadioButton plasticTypeGUIRB5;
    private javax.swing.JRadioButton plasticTypeGUIRBNI;
    private javax.swing.JTextArea textAreaGUI;
    // End of variables declaration//GEN-END:variables
}
    private void systemInit() {
        
        //initialise the model of the list from the GUI which will display the ordered boxes
        orderList = new DefaultListModel();
        orderDetails.setModel(orderList);
        
        //initialise the types of boxes 
        boxTypesInit();

    }

private void pipeTypeInit() {
        //create the array of pipetypes
        PipeTypes = new ArrayList<>();
        pipeGrades = new int[]{1,2,3};
        //create the first boxtype and add it to the ArrayList
        BoxType boxType1 = new SimpleBoxType(cardGrades);
        BoxTypes.add(boxType1);
        //create the 2nd boxtype and add it to the ArrayList
        cardGrades = new int[]{2,3,4};
        BoxType boxType2 = new ColoredBoxType(cardGrades, 1);
        BoxTypes.add(boxType2);
        //create the 3rd boxtype and add it to the ArrayList
        cardGrades = new int[]{2,3,4,5};
        BoxType boxType3 = new ColoredBoxType(cardGrades, 2);
        BoxTypes.add(boxType3);
        //create the 4th boxtype and add it to the ArrayList
        cardGrades = new int[]{2,3,4,5};
        BoxType boxType4 = new ReinforcedBoxType(cardGrades, 2, true, false);
        BoxTypes.add(boxType4);
        //create the 5th boxtype and add it to the ArrayList
        cardGrades = new int[]{3,4,5};
        BoxType boxType5 = new ReinforcedBoxType(cardGrades, 2, true, true);
        BoxTypes.add(boxType5);
        //end boxtypes creation
    }

 /*
     * Checks if there are any set errors and if the box can be supplied
     */
    private void checkErrors() {
        if(!"".equals(heightError.getText()) || !"".equals(widthError.getText()) || !"".equals(lengthError.getText()) ||
           !"".equals(quantityError.getText()) || !"".equals(colourPrintError.getText()) || !"".equals(gradeError.getText()))
        {
            
        }
        else
        {
            //check if the type of box can be supplied
            if(canBeSupplied())
            {
                placeOrder(); // place the order and display the total cost
                resetFields(); // reset the fields before a new order
                boxTypesInit(); // we have to re-initialise the box types because we modified the card grade of a box type when we created the box so that it had only one value in the array
                
            }
            else
            {
                setTypeError("This type of box cannot be supplied ! Please try another configuration !");
            }
        }
    }

 /*
     * Displays the order details on the screen
     */
    private void displayOrderInList() {
        String output = quantity + " x Box (width: " + boxWidth + unitMeasure + "; height: " + boxHeight + unitMeasure +
                             "; length: " + boxLength + unitMeasure + "; grade: " + cardGrade + "; colour: " + colourPrint +"; ";
        if(reinforcedBottom) {
            output = output + "with reinforced bottom; ";
        }
        if(reinforcedCorners) {
            output = output + "with reinforced corners; ";
        }
        if(sealableTops) {
            output = output + "with sealable tops; ";
        }
        output = output + ")";
        orderList.addElement(output);
    }
    
    /*
     * Displays the total cost of the order on the screen
     */
    private void displayTotalCost(double cost) {
        DecimalFormat costFormat = new DecimalFormat("#.##");
        totalCost.setText(costFormat.format(cost));
    }